version: '3'

vars:
  PROJECT_DIR: '{{.ROOT_DIR}}'
  EXAMPLE_NEXTJS_DIR: '{{.ROOT_DIR}}/example-nextjs'
  SRC_DIR: '{{.ROOT_DIR}}/src'
  DIST_DIR: '{{.ROOT_DIR}}/dist'

tasks:
  default:
    desc: Show available tasks (default)
    cmds:
      - task --list
    silent: true

  # Development tasks
  install:
    desc: Install dependencies for main project and example-nextjs
    cmds:
      - bun install
      - cd {{.EXAMPLE_NEXTJS_DIR}} && bun install

  build:
    desc: Build the react-feedback-widget library (TypeScript)
    deps: [_ensure-deps]
    cmds:
      - bun run build
    sources:
      - '{{.SRC_DIR}}/**/*.{ts,tsx}'
      - rollup.config.ts
      - tsconfig.json
      - package.json
    generates:
      - '{{.DIST_DIR}}/**/*.js'

  _ensure-deps:
    desc: Ensure dependencies are installed (internal)
    cmds:
      - bun install
    status:
      - test -d node_modules
    silent: true

  _ensure-example-deps:
    desc: Ensure example-nextjs dependencies are installed (internal)
    deps: [build]
    cmds:
      - cd {{.EXAMPLE_NEXTJS_DIR}} && bun install --force
    status:
      - test -d {{.EXAMPLE_NEXTJS_DIR}}/node_modules
    silent: true

  build:watch:
    desc: Build library in watch mode
    cmds:
      - bun run build --watch

  dev:
    desc: Start example-nextjs with live development
    deps: [build, _ensure-example-deps]
    cmds:
      - cd {{.EXAMPLE_NEXTJS_DIR}} && bun run dev -- -p 3002

  dev:full:
    desc: Run library build in watch mode and nextjs dev server concurrently
    cmds:
      - task: build:watch
      - task: dev
    silent: false

  # Maintenance tasks
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.DIST_DIR}}
      - rm -rf {{.EXAMPLE_NEXTJS_DIR}}/.next

  clean:build:
    desc: Clean and rebuild
    cmds:
      - task: clean
      - task: install
      - task: build

  # Example app tasks
  example:build:
    desc: Build example-nextjs app
    deps: [build]
    cmds:
      - cd {{.EXAMPLE_NEXTJS_DIR}} && bun run build

  example:start:
    desc: Start example-nextjs production server
    deps: [example:build]
    cmds:
      - cd {{.EXAMPLE_NEXTJS_DIR}} && bun run start -- -p 3001

  example:lint:
    desc: Lint example-nextjs app
    cmds:
      - cd {{.EXAMPLE_NEXTJS_DIR}} && bun run lint

  # Utility tasks
  link:local:
    desc: Link local development version to example-nextjs
    cmds:
      - task: build
      - cd {{.EXAMPLE_NEXTJS_DIR}} && bun link react-visual-feedback

  check:
    desc: Run all checks (build, lint)
    cmds:
      - task: build
      - task: example:lint

  info:
    desc: Show project information
    cmds:
      - echo "Project root = {{.PROJECT_DIR}}"
      - echo "Example Next.js = {{.EXAMPLE_NEXTJS_DIR}}"
      - echo "Bun version = $(bun --version)"
      - echo "Node version = $(node --version)"
    silent: false
  # ============================================================================
  # Docker Tasks
  # ============================================================================

  docker:build:
    desc: Build library Docker image
    cmds:
      - docker compose build build

  docker:test:
    desc: Run tests in Docker container
    cmds:
      - docker compose run --rm test

  docker:e2e:
    desc: Run E2E tests in Docker container
    cmds:
      - docker compose run --rm e2e

  docker:shell:
    desc: Open interactive shell in Docker container
    cmds:
      - docker compose run --rm shell

  docker:dev:
    desc: Start development with watch mode in Docker
    cmds:
      - docker compose up dev

  docker:clean:
    desc: Remove Docker images and volumes
    cmds:
      - docker compose down -v --rmi local