version: '3'

# Include shared Taskfiles from the root taskfiles directory
includes:
  docker:
    taskfile: ../../taskfiles/Docker.yml
    optional: true
    vars:
      DOCKER_IMAGE_NAME: feedback-server
      DOCKER_IMAGE_TAG: '{{.DOCKER_IMAGE_TAG | default "latest"}}'

# Package-specific variables
vars:
  PACKAGE_NAME: feedback-server
  SERVER_PORT: '3001'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  # ============================================================================
  # Build & Development
  # ============================================================================

  build:
    desc: Build the server package
    cmds:
      - bun run build
    sources:
      - src/**/*.ts
      - tsconfig.json
    generates:
      - dist/**/*

  dev:
    desc: Start development server with hot reload
    cmds:
      - bun run dev

  start:
    desc: Start production server
    cmds:
      - bun run start

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - bun run typecheck

  lint:
    desc: Run ESLint
    cmds:
      - bun run lint

  # ============================================================================
  # Database
  # ============================================================================

  db:migrate:
    desc: Run database migrations
    cmds:
      - bun run db:migrate

  db:seed:
    desc: Seed the database with sample data
    cmds:
      - bun run db:seed

  db:reset:
    desc: Reset database (drop, migrate, seed)
    cmds:
      - bun run db:reset

  db:studio:
    desc: Open Drizzle Studio for database inspection
    cmds:
      - bun run db:studio

  # ============================================================================
  # Testing
  # ============================================================================

  test:
    desc: Run all tests
    cmds:
      - bun run test

  test:watch:
    desc: Run tests in watch mode
    cmds:
      - bun run test:watch

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - bun run test:coverage

  test:unit:
    desc: Run unit tests only
    cmds:
      - bun vitest run tests/unit

  test:integration:
    desc: Run integration tests only
    cmds:
      - bun vitest run tests/integration

  # ============================================================================
  # TypeSpec / API
  # ============================================================================

  api:generate:
    desc: Generate OpenAPI spec from TypeSpec
    cmds:
      - bun run tsp compile typespec/main.tsp

  api:docs:
    desc: Serve OpenAPI documentation
    cmds:
      - bun run docs:serve

  # ============================================================================
  # Maintenance
  # ============================================================================

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist coverage

  clean:all:
    desc: Clean build artifacts and node_modules
    cmds:
      - rm -rf dist coverage node_modules

  clean:data:
    desc: Clean local data (uploads, sqlite)
    cmds:
      - rm -rf data/*.db uploads/*

  # ============================================================================
  # Quality Checks
  # ============================================================================

  check:
    desc: Run all quality checks (typecheck, lint, test)
    cmds:
      - task: typecheck
      - task: lint
      - task: test

  check:ci:
    desc: Run CI-friendly quality checks
    cmds:
      - bun run typecheck
      - bun run lint
      - bun run test:coverage

  # ============================================================================
  # Docker Tasks
  # ============================================================================

  docker:build:
    desc: Build server Docker image
    cmds:
      - docker compose build server

  docker:up:
    desc: Start server with PostgreSQL in Docker
    cmds:
      - docker compose up -d

  docker:dev:
    desc: Start development server in Docker with hot reload
    cmds:
      - docker compose up dev

  docker:down:
    desc: Stop Docker containers
    cmds:
      - docker compose down

  docker:logs:
    desc: View Docker logs
    cmds:
      - docker compose logs -f

  docker:test:
    desc: Run tests in Docker container
    cmds:
      - docker compose run --rm test

  docker:migrate:
    desc: Run migrations in Docker
    cmds:
      - docker compose run --rm migrate

  docker:shell:
    desc: Open interactive shell in Docker container
    cmds:
      - docker compose run --rm shell

  docker:db:shell:
    desc: Open PostgreSQL shell
    cmds:
      - docker compose exec db psql -U feedback -d feedback

  docker:clean:
    desc: Remove Docker images and volumes
    cmds:
      - docker compose down -v --rmi local

  # ============================================================================
  # Info
  # ============================================================================

  info:
    desc: Show project information
    cmds:
      - |
        echo "Package: {{.PACKAGE_NAME}}"
        echo "Port: {{.SERVER_PORT}}"
        echo "Bun version: $(bun --version)"
        echo "Node version: $(node --version)"
    silent: false
