version: '3'

vars:
  ROOT_DIR: '{{.ROOT_DIR}}'
  LIB_DIR: '{{.ROOT_DIR}}/packages/react-visual-feedback'
  EXAMPLE_DIR: '{{.ROOT_DIR}}/packages/feedback-example'

tasks:
  default:
    desc: Show available tasks (default)
    cmds:
      - task --list
    silent: true

  # Installation
  install:
    desc: Install all workspace dependencies
    cmds:
      - bun install

  _ensure-deps:
    desc: Ensure dependencies are installed (internal)
    cmds:
      - bun install
    status:
      - test -f {{.LIB_DIR}}/node_modules/.bin/rollup
    silent: true

  # Library tasks
  build:
    desc: Build the react-visual-feedback library (TypeScript)
    deps: [_ensure-deps]
    dir: '{{.LIB_DIR}}'
    cmds:
      - bun run build
    sources:
      - '{{.LIB_DIR}}/src/**/*.{ts,tsx}'
      - '{{.LIB_DIR}}/rollup.config.ts'
      - '{{.LIB_DIR}}/tsconfig.json'
      - '{{.LIB_DIR}}/package.json'
    generates:
      - '{{.LIB_DIR}}/dist/**/*.js'

  build:watch:
    desc: Build library in watch mode
    deps: [_ensure-deps]
    dir: '{{.LIB_DIR}}'
    cmds:
      - bun run build:watch

  # Example tasks
  dev:
    desc: Start example app with live development
    deps: [build]  # build already depends on _ensure-deps
    dir: '{{.EXAMPLE_DIR}}'
    cmds:
      - bun run dev

  example:build:
    desc: Build example app
    deps: [build]
    dir: '{{.EXAMPLE_DIR}}'
    cmds:
      - bun run build

  example:start:
    desc: Start example production server
    dir: '{{.EXAMPLE_DIR}}'
    cmds:
      - bun run start

  # Development
  dev:full:
    desc: Run library build in watch mode and example dev server concurrently
    cmds:
      - task: build:watch
      - task: dev

  # Maintenance
  clean:
    desc: Clean all build artifacts
    cmds:
      - rm -rf {{.LIB_DIR}}/dist
      - rm -rf {{.EXAMPLE_DIR}}/.next
      - rm -rf node_modules
      - rm -rf {{.LIB_DIR}}/node_modules
      - rm -rf {{.EXAMPLE_DIR}}/node_modules

  clean:build:
    desc: Clean and rebuild everything
    cmds:
      - task: clean
      - task: install
      - task: build

  # Info
  info:
    desc: Show project information
    cmds:
      - echo "Workspace root = {{.ROOT_DIR}}"
      - echo "Library = {{.LIB_DIR}}"
      - echo "Example = {{.EXAMPLE_DIR}}"
      - echo "Bun version = $(bun --version)"
      - echo "Node version = $(node --version)"

  # Testing
  check:
    desc: Run all checks (build, lint)
    cmds:
      - task: build
      - task: example:build
