#!/usr/bin/env bun
/**
 * Generate TypeScript types from JSON Schema (YAML format)
 *
 * This script:
 * 1. Reads the JSON Schema YAML file generated by TypeSpec
 * 2. Converts it to JSON
 * 3. Uses json-schema-to-typescript to generate TypeScript types
 * 4. Writes the output to the feedback-api-types package
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';
import { compile } from 'json-schema-to-typescript';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
const generatedDir = join(rootDir, '..', 'generated');

async function main() {
  console.log('📦 Generating WebSocket TypeScript types...\n');

  // Read the YAML schema
  const schemaPath = join(generatedDir, 'feedback-api-schemas', 'feedback-api-schemas.yaml');
  console.log(`Reading schema from: ${schemaPath}`);

  const yamlContent = readFileSync(schemaPath, 'utf-8');
  const schema = parseYaml(yamlContent);

  // Extract ServerEvents and ClientCommands schemas
  const serverEventsSchema = schema.$defs?.ServerEvents;
  const clientCommandsSchema = schema.$defs?.ClientCommands;

  if (!serverEventsSchema) {
    throw new Error('ServerEvents schema not found in JSON Schema');
  }

  if (!clientCommandsSchema) {
    throw new Error('ClientCommands schema not found in JSON Schema');
  }

  // Generate TypeScript types for ServerEvents
  console.log('Generating ServerEvents types...');
  const serverEventsTs = await compile(
    {
      ...serverEventsSchema,
      $defs: {
        ...serverEventsSchema.$defs,
        // Include shared types like Feedback from the main schema
        ...schema.$defs,
      },
    },
    'ServerEvents',
    {
      bannerComment: `/**
 * WebSocket Server Events - Auto-generated from TypeSpec
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Generated by: scripts/generate-websocket-types.ts
 * Source: typespec/websocket/events.tsp
 */`,
      additionalProperties: false,
      enableConstEnums: true,
      strictIndexSignatures: true,
      declareExternallyReferenced: true,
      unknownAny: false,
    }
  );

  // Generate TypeScript types for ClientCommands
  console.log('Generating ClientCommands types...');
  const clientCommandsTs = await compile(
    {
      ...clientCommandsSchema,
      $defs: {
        ...clientCommandsSchema.$defs,
        ...schema.$defs,
      },
    },
    'ClientCommands',
    {
      bannerComment: `/**
 * WebSocket Client Commands - Auto-generated from TypeSpec
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Generated by: scripts/generate-websocket-types.ts
 * Source: typespec/websocket/commands.tsp
 */`,
      additionalProperties: false,
      enableConstEnums: true,
      strictIndexSignatures: true,
      declareExternallyReferenced: true,
      unknownAny: false,
    }
  );

  // Write output files
  const outputDir = join(generatedDir, 'feedback-api-types', 'src', 'websocket');
  mkdirSync(outputDir, { recursive: true });

  const eventsOutputPath = join(outputDir, 'events.ts');
  const commandsOutputPath = join(outputDir, 'commands.ts');
  const indexOutputPath = join(outputDir, 'index.ts');

  writeFileSync(eventsOutputPath, serverEventsTs);
  console.log(`✅ Written: ${eventsOutputPath}`);

  writeFileSync(commandsOutputPath, clientCommandsTs);
  console.log(`✅ Written: ${commandsOutputPath}`);

  // Create index file
  const indexContent = `/**
 * WebSocket Types - Auto-generated from TypeSpec
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Generated by: scripts/generate-websocket-types.ts
 */

export * from './events.js';
export * from './commands.js';

// Re-export for convenience
export type {
  ServerEvents,
  FeedbackCreatedEvent,
  FeedbackUpdatedEvent,
  FeedbackDeletedEvent,
  FeedbackBulkUpdateEvent,
  ConnectionAckEvent,
  SubscriptionConfirmedEvent,
  ErrorEvent,
  PongEvent,
} from './events.js';

export type {
  ClientCommands,
  SubscribeCommand,
  UnsubscribeCommand,
  PingCommand,
  AuthenticateCommand,
  SubscriptionFilters,
} from './commands.js';
`;

  writeFileSync(indexOutputPath, indexContent);
  console.log(`✅ Written: ${indexOutputPath}`);

  console.log('\n✨ WebSocket TypeScript types generated successfully!');
}

main().catch((error) => {
  console.error('❌ Error generating types:', error);
  process.exit(1);
});
